# CMake generated Testfile for 
# Source directory: /mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunlinsol/spgmr/serial
# Build directory: /mnt/sdc/SHUD-GPU/InstallSundialsCUDA/builddir/examples/sunlinsol/spgmr/serial
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_sunlinsol_spgmr_serial_100_1_1_100_1e-13_0 "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/builddir/examples/sunlinsol/spgmr/serial/test_sunlinsol_spgmr_serial" "100" "1" "1" "100" "1e-13" "0")
set_tests_properties(test_sunlinsol_spgmr_serial_100_1_1_100_1e-13_0 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/cmake/macros/SundialsAddTest.cmake;161;add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;94;sundials_add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;0;")
add_test(test_sunlinsol_spgmr_serial_100_2_1_100_1e-13_0 "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/builddir/examples/sunlinsol/spgmr/serial/test_sunlinsol_spgmr_serial" "100" "2" "1" "100" "1e-13" "0")
set_tests_properties(test_sunlinsol_spgmr_serial_100_2_1_100_1e-13_0 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/cmake/macros/SundialsAddTest.cmake;161;add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;94;sundials_add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;0;")
add_test(test_sunlinsol_spgmr_serial_100_1_2_100_1e-13_0 "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/builddir/examples/sunlinsol/spgmr/serial/test_sunlinsol_spgmr_serial" "100" "1" "2" "100" "1e-13" "0")
set_tests_properties(test_sunlinsol_spgmr_serial_100_1_2_100_1e-13_0 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/cmake/macros/SundialsAddTest.cmake;161;add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;94;sundials_add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;0;")
add_test(test_sunlinsol_spgmr_serial_100_2_2_100_1e-13_0 "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/builddir/examples/sunlinsol/spgmr/serial/test_sunlinsol_spgmr_serial" "100" "2" "2" "100" "1e-13" "0")
set_tests_properties(test_sunlinsol_spgmr_serial_100_2_2_100_1e-13_0 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/cmake/macros/SundialsAddTest.cmake;161;add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;94;sundials_add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunlinsol/spgmr/serial/CMakeLists.txt;0;")
