# CMake generated Testfile for 
# Source directory: /mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunmatrix/sparse
# Build directory: /mnt/sdc/SHUD-GPU/InstallSundialsCUDA/builddir/examples/sunmatrix/sparse
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_sunmatrix_sparse_400_400_0_0 "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/builddir/examples/sunmatrix/sparse/test_sunmatrix_sparse" "400" "400" "0" "0")
set_tests_properties(test_sunmatrix_sparse_400_400_0_0 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/cmake/macros/SundialsAddTest.cmake;161;add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunmatrix/sparse/CMakeLists.txt;92;sundials_add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunmatrix/sparse/CMakeLists.txt;0;")
add_test(test_sunmatrix_sparse_450_450_1_0 "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/builddir/examples/sunmatrix/sparse/test_sunmatrix_sparse" "450" "450" "1" "0")
set_tests_properties(test_sunmatrix_sparse_450_450_1_0 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/cmake/macros/SundialsAddTest.cmake;161;add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunmatrix/sparse/CMakeLists.txt;92;sundials_add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunmatrix/sparse/CMakeLists.txt;0;")
add_test(test_sunmatrix_sparse_200_1000_0_0 "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/builddir/examples/sunmatrix/sparse/test_sunmatrix_sparse" "200" "1000" "0" "0")
set_tests_properties(test_sunmatrix_sparse_200_1000_0_0 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/cmake/macros/SundialsAddTest.cmake;161;add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunmatrix/sparse/CMakeLists.txt;92;sundials_add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunmatrix/sparse/CMakeLists.txt;0;")
add_test(test_sunmatrix_sparse_6000_350_0_0 "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/builddir/examples/sunmatrix/sparse/test_sunmatrix_sparse" "6000" "350" "0" "0")
set_tests_properties(test_sunmatrix_sparse_6000_350_0_0 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/cmake/macros/SundialsAddTest.cmake;161;add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunmatrix/sparse/CMakeLists.txt;92;sundials_add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunmatrix/sparse/CMakeLists.txt;0;")
add_test(test_sunmatrix_sparse_500_5000_1_0 "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/builddir/examples/sunmatrix/sparse/test_sunmatrix_sparse" "500" "5000" "1" "0")
set_tests_properties(test_sunmatrix_sparse_500_5000_1_0 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/cmake/macros/SundialsAddTest.cmake;161;add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunmatrix/sparse/CMakeLists.txt;92;sundials_add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunmatrix/sparse/CMakeLists.txt;0;")
add_test(test_sunmatrix_sparse_4000_800_1_0 "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/builddir/examples/sunmatrix/sparse/test_sunmatrix_sparse" "4000" "800" "1" "0")
set_tests_properties(test_sunmatrix_sparse_4000_800_1_0 PROPERTIES  _BACKTRACE_TRIPLES "/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/cmake/macros/SundialsAddTest.cmake;161;add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunmatrix/sparse/CMakeLists.txt;92;sundials_add_test;/mnt/sdc/SHUD-GPU/InstallSundialsCUDA/src/cvode-6.0.0/examples/sunmatrix/sparse/CMakeLists.txt;0;")
